### ISSUE TITLE
Issue-add networking to tutorial

### ISSUE THREAD

**Issue by Zeusofsky** [Zeusofsky/blockchain#14]
Automated Review Comments
Issues in README.md:
  - (4, 'Line exceeds 80 characters')
Issues in networking/README.md:
  - (7, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
Issues in networking/main.go:
  - (5, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (74, 'Line exceeds 80 characters')
  - (115, 'Line exceeds 80 characters')
  - (141, 'Line exceeds 80 characters')

**Comment by PhantomFortune** [comment]
I got it.
