### ISSUE TITLE
Issue-add P2P tutorial

### ISSUE THREAD

**Issue by Zeusofsky** [Zeusofsky/blockchain#69]
Automated Review Comments
Issues in p2p/README.md:
  - (8, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
Issues in p2p/main.go:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (27, 'Line exceeds 80 characters')
  - (29, 'Line exceeds 80 characters')
  - (35, 'Hardcoded string found')
  - (51, 'Line exceeds 80 characters')
  - (85, 'Line exceeds 80 characters')
  - (93, 'Line exceeds 80 characters')
  - (95, 'Line exceeds 80 characters')
  - (111, 'Hardcoded string found')
  - (135, 'Hardcoded string found')
  - (214, 'Hardcoded string found')
  - (219, 'Hardcoded string found')
  - (220, 'Hardcoded string found')
  - (221, 'Hardcoded string found')
  - (222, 'Hardcoded string found')
  - (236, 'Hardcoded string found')
  - (273, 'Hardcoded string found')
  - (293, 'Line exceeds 80 characters')
  - (312, 'Line exceeds 80 characters')

**Comment by PhantomFortune** [comment]
I got it.
